version: "3"
services:
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    environment:
      SPOTIFY_CLIENT_ID: "changeMe"
      SPOTIFY_CLIENT_SECRET: "changeMe"
      SPOTIFY_REDIRECT_URI: "http://localhost:8080/spotify"
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'
    volumes:
      - ./public/image:/root/public/image
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app